src/test/java/com/dia/dia_be/repository/ConsultingRepositoryTest.java

> #11 
> consultingRepository save, delete 테스트 추가하였고, 빌드 테스트까지 완료했습니다.

다연 - consulting

---

src/main/java/com/dia/dia_be/exception/CommonErrorCode.java
src/main/java/com/dia/dia_be/exception/ErrorCode.java
src/main/java/com/dia/dia_be/exception/ErrorResponse.java
src/main/java/com/dia/dia_be/exception/GlobalException.java
src/main/java/com/dia/dia_be/exception/GlobalExceptionHandler.java
src/main/java/com/dia/dia_be/exception/PbErrorCode.java
src/main/java/com/dia/dia_be/exception/VipErrorCode.java

> Resolve: #7 
> 전역예외처리기,
도메인별 ErrorCode 정리

[feat] : 전역예외처리

---

src/main/java/com/dia/dia_be/domain/Customer.java
src/main/java/com/dia/dia_be/dto/pb/CustomerDTO.java
src/test/java/com/dia/dia_be/repository/CustomerRepositoryTest.java

> #28 
> CustomerRepositoryTest 작성 ( 연결된 DB로 테스트를 하였기 때문에 테스트DB등을 사용하지 않는다면 BeforeEach로 수정을 하겠습니다!)
> CustomerDTO 작성
> domain-Customer 에 toDto, fromDto 추가

[feat] : CustomerRepositoryTest 작성 & CustomerDTO 작성 & Customer 수정

---

src/main/java/com/dia/dia_be/controller/pb/CustomerController.java
src/main/java/com/dia/dia_be/domain/Customer.java
src/main/java/com/dia/dia_be/dto/pb/CustomerDTO.java
src/main/java/com/dia/dia_be/repository/CustomerRepository.java
src/main/java/com/dia/dia_be/service/pb/impl/CustomerServiceImpl.java
src/main/java/com/dia/dia_be/service/pb/intf/CustomerService.java
src/test/java/com/dia/dia_be/pb/CustomerControllerTest.java
src/test/java/com/dia/dia_be/repository/CustomerRepositoryTest.java

> #32 
> #33 
> #34 
> #35 
**> CustomerController 작성**
```
Issues 32 - 손님 목록 조회
[GET] pb/customer/list
Issues 33 - 손님 검색
[GET] pb/customers/search?name={{customerName}}
Issues 34 - 특정 손님 메모 수정
[POST] pb/customers/{{customerId}}/memo
Issues 35 - 손님 정보 조회
[GET] pb/customers/list/{{customerId}}
```
**> CustomerDTO 작성**
**> Customer(domain) 초기 develop버전과 동일하게 수정**
**> CustomerRepository 작성**
**> CustomerServiceImpl 작성**
**> CustomerService 작성**
**> CustomerControllerTest 작성**

[feat] : CustomerController의 기능, swagger 및 테스트 추가

---

src/test/java/com/dia/dia_be/controller/pb/CustomerControllerTest.java
src/test/java/com/dia/dia_be/controller/vip/ReserveControllerTest.java

[fix] : 컨트롤러 테스트 위치 수정

---

src/main/java/com/dia/dia_be/controller/pb/CustomerController.java
src/test/java/com/dia/dia_be/controller/pb/CustomerControllerTest.java

[style] : Pb와 customer를 1로 지정해둠

---

src/main/java/com/dia/dia_be/controller/vip/VipReserveController.java
src/main/java/com/dia/dia_be/dto/vip/ResponseReserveInfoGetDTO.java
src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java
src/main/java/com/dia/dia_be/service/vip/intf/VipReserveService.java
src/test/java/com/dia/dia_be/controller/vip/VipReserveControllerTest.java

>  #38 
> 상담 예약 전 pbname, vipname 가져오기

[GET] - 상담 예약 전 정보

---

src/main/java/com/dia/dia_be/controller/vip/VipNotificationController.java
src/main/java/com/dia/dia_be/dto/vip/ResponseNotificationGetDTO.java
src/main/java/com/dia/dia_be/repository/NotificationRepository.java
src/main/java/com/dia/dia_be/service/vip/impl/VipNotificationServiceImpl.java
src/main/java/com/dia/dia_be/service/vip/intf/VipNotificationService.java
src/test/java/com/dia/dia_be/controller/vip/VipNotificationControllerTest.java

> #66 현수형작업
> #69 
> #70 
**> VipNotificationController 작성**
Issues 66 - 알림 리스트
[GET] {{base_url}}/vip/notifications
Issues 69 - 전체 알림 삭제
[DELETE] {{base_url}}/vip/notifications/{customerId}
Issues 70 - 전체 알림 읽음
[PATCH] {{base_url}}/vip/notifications/{customerId}/read
**
>ResponseNotificationGetDTO 현수형꺼 사용
>VipNotificationServiceImpl 작성
>VipNotificationService 작성
>VipNotificationControllerTest 작성
> NotificationRepository 코드 추가
**

[feat] : VipNotification의 컨트롤러, 서비스, dto, test 등 추가

---

src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java

[fix] : 대문자, 소문자 오류 수정

---

src/main/java/com/dia/dia_be/controller/vip/VipReserveController.java
src/main/java/com/dia/dia_be/dto/vip/reserveDTO/RequestReserveDTO.java
src/main/java/com/dia/dia_be/dto/vip/reserveDTO/ResponseReserveDTO.java
src/main/java/com/dia/dia_be/dto/vip/reserveDTO/ResponseReserveInfoDTO.java
src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java
src/main/java/com/dia/dia_be/service/vip/intf/VipReserveService.java
src/test/java/com/dia/dia_be/controller/vip/VipReserveControllerTest.java

[feat] : 상담 일정 리스트 가져오기

---

src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
src/main/java/com/dia/dia_be/dto/pb/reservesDTO/ResponseReserveByDateDTO.java
src/main/java/com/dia/dia_be/repository/ConsultingRepository.java
src/main/java/com/dia/dia_be/service/pb/impl/PbReserveServiceImpl.java
src/main/java/com/dia/dia_be/service/pb/intf/PbReserveService.java
src/test/java/com/dia/dia_be/controller/pb/PbReserveControllerTest.java
src/test/java/com/dia/dia_be/repository/ConsultingRepositoryTest.java

> Resolve: #63 
> 특정 상담 날짜 (캘린더) 조회 API 구현

[feat] : 특정 날짜 상담일정(캘린더) 조회

---

src/main/java/com/dia/dia_be/controller/vip/VipPbController.java
src/main/java/com/dia/dia_be/dto/pbProfileDTO/ResponsePbProfileDTO.java
src/main/java/com/dia/dia_be/dto/vip/categoryDTO/ResponseCategoryDTO.java
src/main/java/com/dia/dia_be/dto/vip/notificationDTO/ResponseNotificationDTO.java
src/main/java/com/dia/dia_be/service/vip/impl/VipCategoryServiceImpl.java
src/main/java/com/dia/dia_be/service/vip/impl/VipNotificationServiceImpl.java
src/main/java/com/dia/dia_be/service/vip/impl/VipPbServiceImpl.java
src/main/java/com/dia/dia_be/service/vip/intf/VipCategoryService.java
src/main/java/com/dia/dia_be/service/vip/intf/VipNotificationService.java
src/main/java/com/dia/dia_be/service/vip/intf/VipPbService.java
src/test/java/com/dia/dia_be/controller/vip/VipPbControllerTest.java

> Resolve: #89 
> 특정 VIP의 PB 프로필을 조회하는 API 추가

[feat] : 특정 VIP의 PB 프로필 조회 API 추가

---

src/main/java/com/dia/dia_be/controller/pb/PbJournalController.java
src/main/java/com/dia/dia_be/dto/pb/HashtagDTO/ResponseHashtagDTO.java
src/main/java/com/dia/dia_be/dto/pb/hashtagDTO/ResponseHashtagDTO.java
src/main/java/com/dia/dia_be/dto/pb/productDTO/ResponseProductDTO.java
src/main/java/com/dia/dia_be/dto/pb/profileDTO/ResponseEditProfileDTO.java
src/main/java/com/dia/dia_be/dto/pb/profileDTO/ResponseProfileDTO.java
src/main/java/com/dia/dia_be/repository/ProductRepository.java
src/main/java/com/dia/dia_be/service/pb/impl/PbProductServiceImpl.java
src/main/java/com/dia/dia_be/service/pb/intf/PbProductService.java
src/test/java/com/dia/dia_be/controller/pb/PbJournalControllerTest.java
src/test/java/com/dia/dia_be/repository/ProductRepositoryTest.java

> Resolve: #95 
> 상담 일지 내 PB의 추천 area에서 태그 입력 시 태그 기반으로 table에서 상품들을 검색해 가져오는 api 개발

[feat] : /pb/journals/products?tag= api구현

---

src/main/java/com/dia/dia_be/dto/vip/journalDTO/ResponseJournalDTO.java
src/main/java/com/dia/dia_be/dto/vip/journalDTO/ResponseJournalScriptDTO.java
src/main/java/com/dia/dia_be/dto/vip/journalDTO/ResponseSimpleJournalDTO.java
src/main/java/com/dia/dia_be/dto/vip/reserveDTO/ResponseReserveDTO.java
src/main/java/com/dia/dia_be/service/vip/impl/VipJournalServiceImpl.java
src/main/resources/data.sql

> Resolve: #78 #79 
> 상담일지 스크립트 dto 수정, 상담일지상세 제목 추가,time format 추가, 초기 데이터 수정

[fix] : time format, 일지상세 제목 추가, 스크립트 dto, 데이터 수정

---

src/main/java/com/dia/dia_be/dto/pb/HashtagDTO/RequestHashtagDTO.java
src/main/java/com/dia/dia_be/dto/pb/hashtagDTO/RequestHashtagDTO.java
src/main/java/com/dia/dia_be/dto/pb/profileDTO/ResponseProfileDTO.java
src/test/java/com/dia/dia_be/controller/pb/PbProfileControllerTest.java

> Resolve: #102 
> GET - pb/profile responsebody에 image_url 추가

[fix] : GET - pb/profile image_url 추가

---

src/main/java/com/dia/dia_be/controller/pb/PbKeywordController.java
src/main/java/com/dia/dia_be/dto/pb/keywordDTO/ResponseKeywordDTO.java
src/main/java/com/dia/dia_be/service/pb/impl/PbKeywordServiceImpl.java
src/main/java/com/dia/dia_be/service/pb/intf/PbKeywordService.java
src/test/java/com/dia/dia_be/controller/pb/PbJournalControllerTest.java
src/test/java/com/dia/dia_be/controller/pb/PbKeywordControllerTest.java
src/test/java/com/dia/dia_be/repository/KeywordRepositoryTest.java

> Resolve: #109 
> 딕셔너리(keyword) 페이지의 딕셔너리들 전체 조회, 부분 조회 api 개발

[feat] : get/pb/keywords api 개발

---

src/main/java/com/dia/dia_be/dto/vip/pbProfileDTO/ResponsePbProfileDTO.java
src/main/java/com/dia/dia_be/service/vip/impl/VipPbServiceImpl.java
src/main/java/com/dia/dia_be/service/vip/intf/VipPbService.java

> Resolve: #105 
> PbProfileDTO 충돌 문제 해결

[fix] : PbProfileDTO 충돌 문제 해결

---

src/main/java/com/dia/dia_be/dto/pb/hashtagDTO/ResponseHashtagDTO.java
src/main/java/com/dia/dia_be/dto/pb/profileDTO/ResponseProfileDTO.java
src/test/java/com/dia/dia_be/controller/pb/PbProfileControllerTest.java

> Resolve: #115 
> get/pb/profile ResponseBody
hashtag -> String List로 변경

[fix] : ResponseProfileDTO - hashtag 수정

---

src/main/resources/data.sql

> Resolve: #123 
> PB 프로필 이미지와 상품의 상품 이미지를 이미지서버 url로 변경

[style] : DB 이미지 url을 이미지 서버와 연동

---

src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java

> Resolve: #126 
> 상담 내역 중 오늘도 추가

[fix] : 상담 일정 리스트 오늘 상담도 추가

---

src/main/java/com/dia/dia_be/controller/vip/VipNotificationController.java
src/test/java/com/dia/dia_be/controller/vip/VipNotificationControllerTest.java

> Resolve: #128 #129
> 알림 컨트롤러 mapping 어노테이션 링크 수정

[fix] : 알림 컨트롤러 url 수정

---

src/main/java/com/dia/dia_be/service/vip/impl/VipJournalServiceImpl.java
src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java

> Resolve: #133 
> VIP 메인페이지 상담 내역 및 상담 일정 순서 조정

[fix] : 상담 일정 리스트 및 상담 내역 리스트 순서 조정

---

src/main/java/com/dia/dia_be/controller/pb/PbCustomerController.java
src/main/java/com/dia/dia_be/controller/pb/PbLoginController.java
src/main/java/com/dia/dia_be/dto/pb/loginDTO/LoginDTO.java

> 세션연결관련  LoginDTO를 String에서 Long으로 수정

[fix] : LoginDTO를 String에서 Long으로 수정

---

src/main/java/com/dia/dia_be/controller/pb/PbCustomerController.java
src/main/java/com/dia/dia_be/controller/pb/PbJournalController.java
src/main/java/com/dia/dia_be/controller/pb/PbKeywordController.java
src/main/java/com/dia/dia_be/controller/pb/PbNotificationController.java
src/main/java/com/dia/dia_be/controller/pb/PbProfileController.java
src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
src/test/java/com/dia/dia_be/controller/pb/PbCustomerControllerTest.java
src/test/java/com/dia/dia_be/controller/pb/PbJournalControllerTest.java
src/test/java/com/dia/dia_be/controller/pb/PbKeywordControllerTest.java
src/test/java/com/dia/dia_be/controller/pb/PbNotificationControllerTest.java
src/test/java/com/dia/dia_be/controller/pb/PbProfileControllerTest.java
src/test/java/com/dia/dia_be/controller/pb/PbReserveControllerTest.java

컨트롤러 전체(pbLogin제외)
HttpServletRequest request 인자 추가 및
// 세션 확인 코드 추가
HttpSession session = request.getSession(true);
if (session == null) { // 세션이 없으면 홈으로 이동
return new ResponseEntity<>(null, HttpStatus.FOUND);
}
LoginDTO loginDTO =  (LoginDTO) session.getAttribute(PbSessionConst.LOGIN_PB);
if (loginDTO == null) { // 세션에 회원 데이터가 없으면 홈으로 이동
return new ResponseEntity<>(null, HttpStatus.FOUND);
}
-----------------------------------------------------
테스트컨트롤러(pbLogin제외)
MockHttpSession session;
@BeforeEach
void setupSession() {
// 세션에 로그인 정보를 추가
session = new MockHttpSession();
LoginDTO loginDTO = new LoginDTO(1L);
session.setAttribute(PbSessionConst.LOGIN_PB, loginDTO);
}
와 각각 테스트에 .session(session)) // 세션 추가

Feature/pb http session. 세션들을 추가했고, 그에 맞게 테스트도 세션추가하였습니다(스웨거 안돌아가요. 세션 넣어야함)

---

src/main/java/com/dia/dia_be/controller/pb/PbCustomerController.java
src/main/java/com/dia/dia_be/controller/pb/PbJournalController.java
src/main/java/com/dia/dia_be/controller/pb/PbKeywordController.java
src/main/java/com/dia/dia_be/controller/pb/PbNotificationController.java
src/main/java/com/dia/dia_be/controller/pb/PbProfileController.java
src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java

> 로그인을 제외한 api에 세션없으면 생성 못하도록 수정

[fix] : 로그인을 제외한 api에 세션없으면 생성 못하도록 수정

---

src/main/java/com/dia/dia_be/dto/pb/journalDTO/ResponseJournalDTO.java

> journal 관련해서 응답 받을 내용이 추가적으로 존재하여서 
리스폰스 DTO를 수정했습니다!!

[fix] : dto/pb/journalDTO/ResponseJournalDTO를 수정

---

src/main/java/com/dia/dia_be/dto/pb/journalDTO/ResponseJournalDTO.java

[fix] : 함수 사용 수정

---

src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
src/main/java/com/dia/dia_be/dto/pb/reservesDTO/ResponseReserveDTO.java
src/main/java/com/dia/dia_be/repository/ConsultingRepository.java
src/main/java/com/dia/dia_be/service/pb/impl/PbReserveServiceImpl.java
src/main/java/com/dia/dia_be/service/pb/intf/PbReserveService.java

> Resolve: #149 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

[fix] : getReserve 호출시 customerid도 가져오게끔 controller, dto 수정

---

src/main/java/com/dia/dia_be/dto/pb/reservesDTO/ResponseReserveDTO.java
src/test/java/com/dia/dia_be/controller/pb/PbReserveControllerTest.java

> Resolve: #151 
> ResponseReserveDTO 수정

[fix] : ResponseReserveDTO에 customerId 추가

---

src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
src/main/java/com/dia/dia_be/repository/ConsultingRepository.java
src/main/java/com/dia/dia_be/service/pb/impl/PbReserveServiceImpl.java
src/main/java/com/dia/dia_be/service/pb/intf/PbReserveService.java

[fix] : 불필요한 요소 청소

---

src/main/java/com/dia/dia_be/controller/pb/PbProfileController.java
src/main/java/com/dia/dia_be/repository/HashtagRepository.java
src/main/java/com/dia/dia_be/service/pb/impl/PbProfileServiceImpl.java
src/test/java/com/dia/dia_be/controller/pb/PbProfileControllerTest.java
src/test/java/com/dia/dia_be/repository/HashtagRepositoryTest.java

> Resolve: #155 
> 해시태그 수정이 아니라 추가만 되고 있어서 수정으로 업데이트

[fix] : pbProfile 업데이트 기능 수정 및 테스트 완료

---

src/main/java/com/dia/dia_be/controller/vip/VipCategoryController.java
src/main/java/com/dia/dia_be/controller/vip/VipJournalController.java
src/main/java/com/dia/dia_be/controller/vip/VipLoginController.java

> Resolve: #157 
> VIP Category, Journal, Login 컨트롤러의 return 타입이 <?>였던 것을 전부 타입 지정하였습니다.

[refactor] : Category, Journal, Login return 타입 지정

---

src/main/java/com/dia/dia_be/controller/vip/VipNotificationController.java
src/main/java/com/dia/dia_be/controller/vip/VipPbController.java
src/main/java/com/dia/dia_be/controller/vip/VipReserveController.java

> vip notification, pb, reserve controller return type 수정

[refactor] : vip controller 리팩토링

---

src/main/java/com/dia/dia_be/dto/pb/journalDTO/ResponseJournalDTO.java

> pb -> ResponseJournalDTO.java 수정전 버전으로 돌려졌습니다!

[fix] : ResponseJournalDTO.java 수정 전 버전

---

src/main/java/com/dia/dia_be/dto/pb/reservesDTO/ResponseReserveDTO.java

> Resolve: #164 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

[fix] : dto content 필드 추가

---

src/main/java/com/dia/dia_be/dto/pb/journalDTO/ResponseJournalDTO.java
src/main/java/com/dia/dia_be/dto/pb/productDTO/ResponseProductDTO.java

> Resolve: #166 
> 해당 dto 필드수정해서 더 많은 데이터들을 가져올 수 있게 했습니다

[fix] : ResponseJournalDTO 필드 수정

---

src/main/java/com/dia/dia_be/controller/pb/PbLogoutController.java
src/test/java/com/dia/dia_be/controller/pb/PbLogoutControllerTest.java

> Resolve: #163 
> pb logout api 연결

[feat] : Pb Logout API 및 테스트 코드 완성

---

src/main/java/com/dia/dia_be/dto/pb/profileDTO/ResponseProfileDTO.java
src/main/java/com/dia/dia_be/service/pb/impl/PbProfileServiceImpl.java

[feat] : PbProfile 업로드 관련하여 url 변경!

---

src/main/java/com/dia/dia_be/service/pb/impl/PbJournalServiceImpl.java

> Resolve: #181 
> 일지 작성 완료하면 상담횟수 카운팅되도록 수정

[fix] : 일지 작성 완료하면 상담횟수 카운팅되도록 수정

---

src/test/java/com/dia/dia_be/controller/pb/PbReserveControllerTest.java

> Resolve: #184
> PB ResponseReserveDTO 시간 데이터 형식 수정 후에 
controller test 수정을 미처 놓쳤습니다! 죄송합니다!!

[test] : ResponseReserveDTO 내 시간 형식 변경으로 인한 테스트 코드 수정

---

src/main/java/com/dia/dia_be/WebDriverConfig.java
src/main/java/com/dia/dia_be/service/crawling/IssueCrawlingScheduler.java
src/main/java/com/dia/dia_be/service/crawling/impl/IssueCrawlingServiceImpl.java

> Resolve: #191 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

[fix] : issuecrawling 코드 주석처리

---

src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java

> Resolve: #194 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

[fix] : approveReserves 반환 body string -> status code

---

src/main/java/com/dia/dia_be/controller/vip/VipJournalController.java
src/main/java/com/dia/dia_be/controller/vip/VipNotificationController.java
src/main/java/com/dia/dia_be/controller/vip/VipReserveController.java
src/main/java/com/dia/dia_be/service/vip/impl/VipJournalServiceImpl.java
src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java
src/main/java/com/dia/dia_be/service/vip/intf/VipJournalService.java
src/main/java/com/dia/dia_be/service/vip/intf/VipReserveService.java
src/test/java/com/dia/dia_be/controller/vip/VipJournalControllerTest.java
src/test/java/com/dia/dia_be/controller/vip/VipNotificationControllerTest.java
src/test/java/com/dia/dia_be/controller/vip/VipReserveControllerTest.java

> Resolve: #204 
> 컨트롤러에 세션 추가 및 테스트코드 수정

[feat] : 로그인 관련 컨트롤러 및 테스트코드 수정

---

src/main/java/com/dia/dia_be/dto/pb/reservesDTO/ResponseReserveDTO.java

> Resolve: #206 
> responseReserveDTO 에 categoryName 필드 수정, isUpcomming 필드 simply

[fix] : responseReserveDTO에 cateogoryName 필드 추가

---

.github/workflows/deploy.yml
build.gradle

[chore] : build.gradle에 빌드 시 테스트 생략

---

src/main/java/com/dia/dia_be/WebDriverConfig.java

release 0.0.7.2

---

src/main/java/com/dia/dia_be/controller/pb/PbJournalController.java
src/main/java/com/dia/dia_be/repository/JournalRepository.java
src/main/java/com/dia/dia_be/service/pb/impl/PbJournalServiceImpl.java
src/main/java/com/dia/dia_be/service/pb/intf/PbJournalService.java

> Resolve: #218 
>스크립트 삭제 DELETE API 개발, service repository delete 기능 추가

[feat] : 스크립트 삭제 DELETE API 개발

---

src/main/java/com/dia/dia_be/controller/pb/PbProfileController.java
src/main/java/com/dia/dia_be/websocket/WebSocketConfig.java

> Resolve: 
> websocket origin 수정

[feat] : 웹소켓 config 수정

---

src/main/java/com/dia/dia_be/WebDriverConfig.java
src/main/java/com/dia/dia_be/repository/IssueRepository.java
src/main/java/com/dia/dia_be/repository/ProductRepository.java

> Resolve: #222 
> 기존 sql은 로컬 작업으로 대소문자 구분 없어도 작동이 되었는데, 현재는 리눅스 rds로 연결되므로 소문자로 테이블이 들어가 있음. 이에 따라 product와 issue 레포지토리의 sql을 전부 소문자로 변경.

[fix] : product, issue 레포의 sql 소문자로 변경

---

src/main/java/com/dia/dia_be/WebDriverConfig.java

> Resolve: #224 
> WebDriverConfig 주석 해제

[fix] : WebDriverConfig 주석 제거

---

src/main/resources/data.sql
src/main/resources/schema.sql

> Resolve: 
> 고객 상담 횟수 수정 및 상담 완료 여부 수정

[style] : 데이터 수정

---

src/main/java/com/dia/dia_be/WebDriverConfig.java
src/main/java/com/dia/dia_be/controller/pb/PbCustomerController.java
src/main/java/com/dia/dia_be/controller/pb/PbJournalController.java
src/main/java/com/dia/dia_be/controller/pb/PbKeywordController.java
src/main/java/com/dia/dia_be/controller/pb/PbLoginController.java
src/main/java/com/dia/dia_be/controller/pb/PbLogoutController.java
src/main/java/com/dia/dia_be/controller/pb/PbNotificationController.java
src/main/java/com/dia/dia_be/controller/pb/PbProfileController.java
src/main/java/com/dia/dia_be/controller/pb/PbReserveController.java
src/main/java/com/dia/dia_be/controller/vip/VipCategoryController.java
src/main/java/com/dia/dia_be/controller/vip/VipJournalController.java
src/main/java/com/dia/dia_be/controller/vip/VipLoginController.java
src/main/java/com/dia/dia_be/controller/vip/VipNotificationController.java
src/main/java/com/dia/dia_be/controller/vip/VipPbController.java
src/main/java/com/dia/dia_be/controller/vip/VipReserveController.java
src/main/java/com/dia/dia_be/dto/pb/availabilityDTO/RequestAvailabilityDTO.java
src/main/java/com/dia/dia_be/dto/pb/customerDTO/RequestCustomerDTO.java
src/main/java/com/dia/dia_be/dto/pb/hashtagDTO/RequestHashtagDTO.java
src/main/java/com/dia/dia_be/dto/pb/journalDTO/RequestJournalDTO.java
src/main/java/com/dia/dia_be/dto/pb/journalDTO/ScriptRequestDTO.java
src/main/java/com/dia/dia_be/dto/pb/loginDTO/LoginForm.java
src/main/java/com/dia/dia_be/dto/pb/notificationDTO/RequestNotificationDTO.java
src/main/java/com/dia/dia_be/dto/pb/profileDTO/RequestProfileDTO.java
src/main/java/com/dia/dia_be/dto/vip/categoryDTO/ResponseCategoryDTO.java
src/main/java/com/dia/dia_be/dto/vip/loginDTO/RequestVipSignUpDTO.java
src/main/java/com/dia/dia_be/dto/vip/loginDTO/VipLoginForm.java
src/main/java/com/dia/dia_be/dto/vip/reserveDTO/RequestReserveDTO.java
src/main/java/com/dia/dia_be/service/vip/impl/VipReserveServiceImpl.java

> Resolve:
> 스웨거 문서 정리를 위해 컨트롤러 및 dto 수정

Refactor/swagger UI

---

src/main/java/com/dia/dia_be/WebDriverConfig.java
src/main/java/com/dia/dia_be/controller/pb/PbCustomerController.java
src/main/java/com/dia/dia_be/repository/CustomerRepository.java
src/main/java/com/dia/dia_be/service/pb/impl/PbCustomerServiceImpl.java
src/main/java/com/dia/dia_be/service/pb/intf/PbCustomerService.java
src/test/java/com/dia/dia_be/controller/pb/PbCustomerControllerTest.java

> Resolve: #234 
> pb에 따른 손님을 불러오지 못하는 문제 해결

[fix] : pb의 customer가 뜨도록 수정

---

src/main/java/com/dia/dia_be/WebDriverConfig.java
src/main/java/com/dia/dia_be/service/crawling/IssueCrawlingScheduler.java
src/main/java/com/dia/dia_be/service/crawling/impl/IssueCrawlingServiceImpl.java
src/main/java/com/dia/dia_be/service/crawling/intf/IssueCrawlingService.java

[chore] : local 환경 설정
